language: perl
script: prove -lr t
install:
  - cpanm -n -q --skip-satisfied --installdeps .
perl:
  # Make sure that very old + very new + one threaded perl is
  # amongst the first five --- travis-ci tests only five
  # configurations at a time.
  - "5.8"
  - "5.10"
  - "5.26"
  - "5.24"
  - "5.24-shrplib"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
# notifications:
#   irc:
#     channels:
#       - "irc.perl.org#toolchain"
#     on_success: change
#     on_failure: always
