addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  # Make sure that very old + very new + one threaded perl is
  # amongst the first five --- travis-ci tests only five
  # configurations at a time.
  - "5.8"
  - "5.10"
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.24-shrplib"
  - blead       # builds perl from git
  - dev         # latest point release
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
# notifications:
#   irc:
#     channels:
#       - "irc.perl.org#toolchain"
#     on_success: change
#     on_failure: always
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
