--- #YAML:1.0
name:                File-Temp
version:             0.19
abstract:            return name and handle of a temporary file safely
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Fcntl:                         1.03
    File::Path:                    0
    File::Spec:                    0.8
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Tim Jenness <tjenness@cpan.org>
